version: '3.5'

services:
  server:
    container_name: server
    build: ./server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
  client:
    container_name: client
    build: ./client
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    depends_on:
      - server