version: '3.5'

services:
  server:
    image: platardev/server:latest
    container_name: server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
  client:
    image: platardev/client:latest
    container_name: client
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    depends_on:
      - "server"